### ISSUE TITLE
[TEST] 회원 관련 통합 테스트코드 작성

### ISSUE THREAD

**Issue by Leeyoujin00** [culticare-app/msa-member#13]
## ⚒️ Issue

원 관련 통합 테스트코드 작성

## 📝 To-do

- [x] 회원가입 테스트코드 작성
- [x] 로그인 테스트코드 작성
- [x] 로그아웃 테스트코드 작성
- [x] 아이디 중복 테스트코드 작성
